export {
  SeatSchema,
  SeatStatusItemSchema,
  SeatsResponseSchema,
  SeatStatusResponseSchema,
  ReserveSeatRequestSchema,
  ReserveSeatResponseSchema,
  ReleaseSeatRequestSchema,
  ReleaseSeatResponseSchema,
  ValidateSelectionRequestSchema,
  ValidateSelectionResponseSchema,
  type Seat,
  type SeatStatusItem,
  type SeatsResponse,
  type SeatStatusResponse,
  type ReserveSeatRequest,
  type ReserveSeatResponse,
  type ReleaseSeatRequest,
  type ReleaseSeatResponse,
  type ValidateSelectionRequest,
  type ValidateSelectionResponse,
} from '@/features/seats/backend/schema';
